### ISSUE TITLE
Tag cloud does not work

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#11]
Clicking on a tag in the cloud causes an error:

`0 - Serialization of 'Closure' is not allowed`

UPD. All tags in articles and category links do not work now.

**Comment by eworkers** [comment]
actually you were right about #9 in the first place! [from what it looks it might be Joomla problem but it needs further investigation! ](https://github.com/joomla/joomla-cms/issues?q=is%3Aissue+Serialization+of+%27Closure%27+is+not+allowed)

We were able to get around for most of the extended part, but not for the latest items (from users or category)! This should fix your issue for itemlist (tag and all other things, #9 was still there) but not for latest items, not sure if we should submit the commit or take some time to resolve for all

**Comment by cmirnow** [comment]
The Joomla team is slow. :) How about a workaround?
In any case, please let me know your decision here, it's really interesting.
