### ISSUE TITLE
Component installation error

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#12]
Update error K2ForJ4:

`0 version_compare(): Argument #3 ($operator) must be a valid comparison operator`

UPD. Component can not be uninstalled by means of Joomla.

**Comment by eworkers** [comment]
This happens when installing or removing k2? not sure which one do you mean
I wasn't able to reproduce on both scenarios (install and uninstall)
Are you able to reproduce? if so, can you please share the steps so we can look into the issue?

**Comment by eworkers** [comment]
never mind, stupid typo mistake, pushing fix now
