### ISSUE TITLE
Unable to turn off material publication

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#13]
After upgrading from K2 to K2ForJ4 (Joomla 3.10.11, php 8.1) can not turn off publishing K2 material (expected behavior - '404 - Material not found').

**Comment by eworkers** [comment]
Do you mean that unpublished items still shows on frontend when caching is enabled?

If that what you meant, I think this problem also exists for k2 official version on Joomla 3.10.11 for all sort of operations [publish, unpublish, new, edit, delete... All not triggering cache clean ] (not sure if php version makes any difference).

Can you please test this issue for official K2 version on  Joomla 3.10.11 and report back so we can handle this matter accordingly?

**Comment by cmirnow** [comment]
I'm sorry, I didn't explain the problem well. Caching has nothing to do with this error. Of course, I disabled the Joomla cache (Joomla 4, K2ForJ4, php 8.1) before describing the problem here.

At the same time, the caching was enabled during another test - Joomla 3.10.11, K2 v.2.10.3 - this problem does not exist. After clearing the cache Joomla shows error 404, "Material not found".

**Comment by eworkers** [comment]
@cmirnow Looks like we might be lost in translation in here :relaxed:
Help me out so we can fix this matter

1. So this is happening on J4? on J3.10.11? on both?
2. It is nothing related at all to caching?
3. Can you help me reproduce the issue on my own? ( provide me with a step by step guide to encounter the issue? )
and thanks again @cmirnow ! as always

**Comment by cmirnow** [comment]
OK, no problem.
Reproduce:

1. Install Joomla 3.10.11 (php 7.4).
2. Install K2 v.2.10.3. The default cache is off.
3. Add new category K2.
4. Add new item K2.
5. Create a menu item for the new item.
6. Turn off publishing here: /administrator/index.php?option=com_k2&view=items
7. Go to the page of the new article.

![1](https://user-images.githubusercontent.com/10660173/203841983-28ef6ba2-3a9c-4170-9a46-eb379eb3e5aa.png)

8. Install K2ForJ4.
9. Refresh the page of the new article.

![2](https://user-images.githubusercontent.com/10660173/203842040-04056f53-fdf6-4c6d-b971-a4eae9b5f5d4.png)

For php 8.1 (K2ForJ4) the result is similar.
