### ISSUE TITLE
"K2 User" profile does not work correctly

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#16]
"My account" options in the "K2 User" profile ( /index.php/your-profile ) don't work: it's impossible to upload an avatar and define gender. Php 8.0 or 8.1, Joomla 4.2.5, K2ForJ4. Caching is disabled.

Note. I failed to reset token (Joomla API Token section) on this page -  /index.php/your-profile. Selecting "Yes" of the "Reset" trigger and "Save" does not replace the token.

[[4.0] API: Token can not be reset](https://github.com/joomla/joomla-cms/issues/28962)

P.S. I think I'm beginning to understand why Fotis Evangelouis delaying a new release. :D

**Comment by cmirnow** [comment]
Interestingly, I can change Joomla API Token in the Joomla User Manager. But in the K2 user profile I can't do that...

**Comment by cmirnow** [comment]
Reset button (Joomla API Token section) still does not work.

**Comment by eworkers** [comment]
> Reset button (Joomla API Token section) still does not work.

Noted and opened in here #18
