### ISSUE TITLE
The "Moderate comments to my published items" option causes errors

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#17]
PHP 8.1, Joomla 4.2.5, K2ForJ4.

Reproduce:

1. Publish module K2 User
2. Log in through the module
3. Click the link  "Moderate comments to my published items"

The **Unpublish** and **Flag as Spammer** triggers do not work:

```
VM297 comments:290 Uncaught ReferenceError: listItemTask is not defined
    at HTMLAnchorElement.onclick (VM297 comments:290:157)
```

![issue_k2](https://user-images.githubusercontent.com/10660173/204217107-80fefd12-8f0c-4ddb-b35f-d32cd4ece3b0.png)

> WARNING: This action will block the user and also unpublish all of their items and comments. Are you sure?
> You cannot edit two comments at the same time!

**Comment by eworkers** [comment]
For the publish/unpublish issue a commit has been pushed to fix, as for the (Flag as spammer) is this also a k2 official version issue on J3? 
Can you please test this for k2 official version so we can fix properly.

**Comment by cmirnow** [comment]
Right. I confirm it. As for the (Flag as spammer) is a problem with the official K2 version. Moreover, unlike K2ForJ4, K2 generates not 2 but 3 warnings! I am surprised.

![new_issue_k2](https://user-images.githubusercontent.com/10660173/204351478-3f5e75dc-583f-4d24-9def-6bc6724e755d.png)
