### ISSUE TITLE
The checkbox of the K2 Comments module does not work. Problem with official K2

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#19]
In K2 Comments module, "Top Commenters -> Commenter avatar -> Hide/Show" option is subordinate to "Latest Comments -> Commenter avatar -> Hide/Show" option. In other words, it doesn't work.

**Comment by eworkers** [comment]
Are you sure that comments are not empty? and the items (or the users) with the comments were not disabled | deleted | flaged as spam?

**Comment by cmirnow** [comment]
Yes. I'm sure. If "Top commenters" functionality is enabled (the "Select module functionality" option) - the avatar display control is implemented in the "Latest Comments" tab.

Note. The comment was left by me as a superuser.

**Comment by eworkers** [comment]
I think I misunderstood at first, please check if the last commit fix the issue, if not reopen the issue again

**Comment by cmirnow** [comment]
Done. Problem solved.
