### ISSUE TITLE
Error 1064, an error in SQL syntax

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#22]
K2 Comments -> Select module functionality -> Latest Comments.
Feed Link does not work (The requested page can't be found).

**Comment by eworkers** [comment]
Unable to reproduce! can you double check while making sure that you are using the latest Dev version

**Comment by cmirnow** [comment]
I confirm the problem. You can take a look here:
http://cq71437.tw1.ru
[Click on the K2 Comments module feed icon](http://cq71437.tw1.ru/index.php/component/k2/itemlist?format=feed&moduleID=94).

`1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1`

If necessary, I will give you full access to this test site.

**Comment by eworkers** [comment]
does the last push solve this for you? if so, please go ahead and close the issue yourself, if not => please inform us in here.
and again thank you @cmirnow !

**Comment by cmirnow** [comment]
The fix solves the problem. Closed.

**Comment by cmirnow** [comment]
Thanks to the K2ForJ4 development team for their excellent work.
