### ISSUE TITLE
Recaptcha 2.0 does not work

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#23]
How to reproduce:

1. Configure recaptcha (Joomla 3.10.11, php 7.4, K2 v.2.10.3).
2. Leave a comment. Make sure that recaptcha works properly.
3. Install K2ForJ4.
4. Reload the page. Try again to leave a comment.
5. Error: "The anti-spam settings for this website are not yet properly configured and comments cannot yet be published. Please notify the site administrator".

**Comment by cmirnow** [comment]
I'm surprised really. It seems that until recently this problem did not exist... OK, step by step.

Install Joomla 3.10.11 (php 7.4).
Go to the admin panel.
Install K2 v.2.10.3
Create a category in K2.
Create an Article in K2.
Create a K2 article menu item.
Enter the recaptcha key and enable CAPTCHA - reCAPTCHA plugin.
Global Configuration -> Site Settings -> Default Captcha -> enter CAPTCHA - reCAPTCHA.
Components -> K2 -> Settings -> Site -> Comments -> Anti-spam protection enter Google Recaptcha.
Components -> K2 -> Settings -> Site -> Comments -> Anti-spam settings enter recaptcha keys.
Open a new K2 article page and write a comment:

![recaptcha1](https://user-images.githubusercontent.com/10660173/204888371-de1ddbc7-910d-4bb5-ba77-8c032cf2fd27.png)


Extensions -> Manage -> Install -> Upload Package File - > K2ForJ4-master.zip
Reload the K2 article page.
Write a comment:

![recaptcha2](https://user-images.githubusercontent.com/10660173/204888456-30e05d33-a03d-4a94-96b4-af3f14c47d73.png)

**Comment by eworkers** [comment]
Thought you meant captcha box not appearing, our mistake. Does the last push fix your issue?

**Comment by cmirnow** [comment]
Yes. It works.
