### ISSUE TITLE
Error JString

### ISSUE THREAD

**Issue by volfoni68** [eworkers/K2ForJ4#24]
Hello,
I followed your instructions, everything went well. But I have Class "JString" not found error with SP Page Builder in backend and frontend. Thank you for your work.

**Comment by eworkers** [comment]
Sounds like this is SP Page Builder related issue! make sure you are using an SP Page Builder version compatible with joomla 4, => update SP Page Builder to the latest version and try again. Closing this as it is not replated to K2ForJ4
