### ISSUE TITLE
Edit Menu categorie

### ISSUE THREAD

**Issue by volfoni68** [eworkers/K2ForJ4#27]
The selection of one or more categories of K2 is not saved.
In the browser console "Error Uncaught TypeError: window.addEvent is not a function"

**Comment by eworkers** [comment]
please share more info, on what Joomla version?
Can you provide some screenshots for the process?

**Comment by volfoni68** [comment]
Joomla 4.2.5
Whatever the selected category, the menu link is incorrect or 404 error.
Screenshot : [https://dev.imdevclients.net/k2.jpg](url)

**Comment by eworkers** [comment]
Does the last push solve your problem?

**Comment by volfoni68** [comment]
Yep many thanks !
Have a nice day!
