### ISSUE TITLE
0 - call_user_func_array()

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#31]
After upgrading to Joomla 4 (php 8.0, K2ForJ4) [this bug](https://github.com/eworkers/K2ForJ4/issues/29) occurs as follows:

`0 - call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "k2_item431react-componentwillmount-componentdidmounttagitemlist" not found or invalid function name`

Note. "react-componentwillmount-componentdidmount" - the alias of one of the articles of the tag link.

**Comment by cmirnow** [comment]
I installed the latest revision of K2ForJ4 on Joomla 3.10.11, problem solved (probably). Then I upgraded to Joomla 4.2.5, and it's the same:
`0 call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "k2_item_2_second_tag_itemlist_" not found or invalid function name`
http://cq71437.tw1.ru/index.php/component/k2/itemlist/tag/tag

**Comment by eworkers** [comment]
> I installed the latest revision of K2ForJ4 on Joomla 3.10.11, problem solved (probably). Then I upgraded to Joomla 4.2.5, and it's the same (php 8.0, 8.1): `0 call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "k2_item_2_second_tag_itemlist_" not found or invalid function name` http://cq71437.tw1.ru/index.php/component/k2/itemlist/tag/tag

did you clear the cache after upgrade? Can you please clear the cache and try again

**Comment by eworkers** [comment]
how about the last push?

**Comment by cmirnow** [comment]
No. Unfortunately, I was able to reproduce the error. 

`0 call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "k2_item_2_second_tag_itemlist_Itemid_101_" not found or invalid function name`

**Comment by eworkers** [comment]
> [Take a look](http://cq71437.tw1.ru/index.php/component/k2/itemlist/tag/newtag).

bare with us @cmirnow , let's assume that in the example above you didn't have a tag named 'tag', will the problem remain?
in other words can you remove the tag called tag or renamed to something else, add as many new tags as you want, clear the cache and try again? Just to help us understand the problem better in order to solve.

**Comment by cmirnow** [comment]
Done.
Here's probably...
http://cq71437.tw1.ru/index.php/component/k2/itemlist/tag/fourthtag
http://cq71437.tw1.ru/index.php/component/k2/itemlist/tag/thirdtag

**Comment by eworkers** [comment]
we have a new push, can you please test it? hopefully we can close caching issues for good this time!

**Comment by cmirnow** [comment]
This fix seems to solve all problems. Closed.
