### ISSUE TITLE
Email link in K2ForJ4 articles doesn't work

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#34]
`404 Component not found.`
php 8, Joomla 4

**Comment by cmirnow** [comment]
Hmm. You're right. But the email link just was, I checked it several times after updating to Joomla 4 (the cache was cleared).... maybe I will try to restore the sequence of my actions... that's interesting.

**Comment by cmirnow** [comment]
No, it wasn't my hallucination. :)
Browser cache, probably. 
Take a look. Joomla after updating from 3.10.11 to 4.2.5. 
Doesn't matter, though, since it's not a bug.

![Screenshot_20221208_002237](https://user-images.githubusercontent.com/10660173/206299881-2604e1f8-4883-493e-b584-ee1a7635a1a3.png)

**Comment by eworkers** [comment]
I think what happened is that after upgrade browser cache still existed, probably because configured cache time was higher than upgrade time cost. ctrl +f5 should have been enough to mask such problem. basically it is an expired cache problem
