### ISSUE TITLE
Problems with current version

### ISSUE THREAD

**Issue by tdrugan** [eworkers/K2ForJ4#37]
Attachments are not uploaded and no atttachment is done to the K2 item.
Incompatibility with SEO.
Incorrect link generated for the K2 categories in new menu item.

**Comment by eworkers** [comment]
> Attachments are not uploaded and no atttachment is done to the K2 item.

please make sure you have cleared your browser cache after the installation 

> Incompatibility with SEO. Incorrect link generated for the K2 categories in new menu item.

Please share your Joomla & php version and separate issues and provide more explanation and details about each issue and screenshot(s) when it's possible

**Comment by tdrugan** [comment]
I have tried on different computers, I cannot attach any file on Joomla 4.4 or Joomla 5 with PHP 8.1.25.

If I try to edit a K2 Category I get:

![edit category](https://github.com/eworkers/K2ForJ4/assets/10137701/ef94e656-17fa-4540-9f8d-50bf815335e5)

If I try to make a new menu entry for k2 Categories I get:

![J4 4 new menu item K2 Categories](https://github.com/eworkers/K2ForJ4/assets/10137701/60fb806b-5009-4bfa-99b8-e57118dad9a6)

and not:

![J4 4 new menu item K2 Categories](https://github.com/eworkers/K2ForJ4/assets/10137701/981f1439-665a-4afa-bd80-0a4143ac858b)

**Comment by eworkers** [comment]
> I have tried on different computers, I cannot attach any file to a K2 item on Joomla 4.4 or Joomla 5 with PHP 8.1.25.

I can't reproduce the error nor the attachment issue, do you have third party plugins installed? if so try to disable them one by one and test at each time
As for the error, please enable system debug in joomla global configuration and set error display to maximum then share the error screenshot again

> If I try to edit a K2 Category I get:

Does the last push solve your mentioned issue above?

**Comment by tdrugan** [comment]
For attaching the file I get from time to time an File Error message, but no attachement is saved.
For K2 Category edit I get an: An error has occurred. 0 Call to a member function loadArray() on null
[Uploading administrative logs.zip…]()

**Comment by eworkers** [comment]
> For attaching the file I get from time to time an File Error message, but no attachement is saved.

Can you please open a new issue for this so we can deal with different issues separately, and you please mention the error message you are getting when you open the issue

> For K2 Category edit I get an: An error has occurred. 0 Call to a member function loadArray() on null
What editor are you using? and does the last commit solve your issue?

**Comment by eworkers** [comment]
> For attaching the file I get from time to time an File Error message, but no attachement is saved.

Can you please open a new issue for this so we can deal with different issues separately, and you please mention the error message you are getting when you open the issue

> For K2 Category edit I get an: An error has occurred. 0 Call to a member function loadArray() on null

What editor are you using? and does the last commit solve your issue?

**Comment by tdrugan** [comment]
With the lastest version I can edit and create new K2 Categories both with JCE and TinyMCE editors.
