### ISSUE TITLE
SigPRO gallery won't upload

### ISSUE THREAD

**Issue by krmrtrzv** [eworkers/K2ForJ4#39]
Hello eworkers, congrats for this intermediate solution! I confirm everything works properly after your last commits. 
The only thing I am struggling with is to make the SigPRO integration working. An attempt to upload an archive gives error 0 Class JRequest unknown - in /administrator/com_k2/models/item.php 485 "!JRequest::extract".

**Comment by bossies** [comment]
thanks for the work, are there any alternative to use for SigPRO as I use it on all my items and thus are still unable to upgrade to J4?
