### ISSUE TITLE
Calling individual extrafields do not work

### ISSUE THREAD

**Issue by krmrtrzv** [eworkers/K2ForJ4#41]
In K2 / J3 it was possible to call individual extra-fields by name or alias, like:
<?php if($this->item->extraFields->MyExtraFirldName->name): ?>
<?php echo $this->item->extraFields->MyExtraFirldName->value; ?>.
This functionality seems not working in J4 or there is a new way for the call?

**Comment by eworkers** [comment]
share you code please so we can take a look, this API has not been changed.
note that to get the extra-field name:
$this->item->extraFields->EXTRAFIELD_ALIAS->name; 
note this **EXTRAFIELD_ALIAS**, it is not **YourExtraFirldName**, it is your **YourExtraFieldAlias**
and to get the the value of it:
$this->item->extraFields->EXTRAFIELD_ALIAS->value;

**Comment by krmrtrzv** [comment]
Thanks so much!
In the meantime I discovered another way of calling individual extra
fields. Here is my code:

<?php if ($this->item->params->get('itemExtraFields') &&
isset($this->item->extra_fields) && count($this->item->extra_fields)): ?>
            
                <ul>
                <?php foreach ($this->item->extra_fields as $key =>
$extraField): ?>
                    <?php if ($extraField->value != ''): ?>
                    <?php if ($extraField->name == 'MyExtraFieldName'): ?>
<li class="list-inline-item"><?php echo $extraField->value; ?></li>
                    <?php endif; ?>
...
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
        <?php endif; ?>

It works perfectly, Please close this issue and enormous thank you for your
contribution!
