### ISSUE TITLE
Field 'checked_out_time' doesn't have a default value. Unable to use K2forJ4 now

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#43]
![k2_error](https://github.com/eworkers/K2ForJ4/assets/10660173/8dd5de9d-c978-4301-bdc7-858a8c16128f)

Creating a new K2 article is impossible: **Field 'checked_out_time' doesn't have a default value**.
Unfortunately, this error makes it impossible to use **K2forJ4** at the moment. The error level is critical.

```
$ mariadb -V
mariadb from 11.1.3-MariaDB, client 15.2 for Linux (x86_64) using  EditLine wrapper
```

**Comment by the-one-antonio** [comment]
Thanks for noting this.  I am also experiencing this issue.

**Comment by cmirnow** [comment]
This is weird. I didn't see this error the last time I tested this fork. This problem did not exist at that time. @eworkers , perhaps you can tell me what the cause of the problem is?

**Comment by eworkers** [comment]
can you take a look at this closed [issue](https://github.com/eworkers/K2ForJ4/issues/38#issuecomment-1812861915) and see if it helps?

**Comment by eworkers** [comment]
does 022da7c solve you issue?

**Comment by cmirnow** [comment]
> does [022da7c](https://github.com/eworkers/K2ForJ4/commit/022da7cd9d59e8172adff3304f12742617527611) solve you issue?

Can you please tell me, can I apply this update to a broken version of K2ForJ4 (Joomla 4) using which K2 articles update has been done before?
Or do I need to do the K2 articles update again (from Joomla 3 to Joomla 4) using this?

**Comment by cmirnow** [comment]
> does [022da7c](https://github.com/eworkers/K2ForJ4/commit/022da7cd9d59e8172adff3304f12742617527611) solve you issue?

Yes, that problem has been solved. Thank you.
