### ISSUE TITLE
Menu Item pointing to single category results in 404 error

### ISSUE THREAD

**Issue by krmrtrzv** [eworkers/K2ForJ4#47]
Hello, as suggested by you, I open a new issue here. 
A menu Item pointing to a single k2 category results in a 404 error, due to wrong SEO address:
the url points to https://mysite.com/en/menu_link_alias/category/catID
instead of just: https://mysite.com/en/menu_link_alias
When I change the URL manually, I do see items list from the correct category, but the template selected in the category settings is omitted and the page uses the default k2 template. 

My setting is: Joomla 5.0.2; 10.6.16-MariaDB; PHP Version 8.1.26; Web Server Apache. 
Cache is disabled, plugin JCH Optimize is disabled
SEO settings in K2 backend are:
Enforce SEF URL character replacements - enabled
Custom (advanced) SEF settings for K2 URLs - disabled.
I migrated the J3 site installing K2ForJ4 on J3, and then reinstalling it again on J4, also reinstalled it again this weekend with all new commits, I believe.

Here is a link to the actual issue: https://terziev.info/en/works2/category/4

**Comment by eworkers** [comment]
please update to the last version and report back.

**Comment by eworkers** [comment]
considered fixed in 324d935 , if commit does not solve your issue, please re-open

**Comment by krmrtrzv** [comment]
Yes, Thank you! Everything is working now as expected. Looking forward the
discussion on the future of K2ForJ4

Krassimir Terziev
https://www.terziev.info
