### ISSUE TITLE
0 - call_user_func_array(): Argument #1 ($callback) must be a valid callback

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#52]
After the last [push](https://github.com/eworkers/K2ForJ4/commit/630a3a7ad2e247b1bf4d32c40b5e810ee1027e27) I get this error on the page generated by the tag:

`0 - call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "439_Скрипт для преобразования текста в аудио. Google Cloud Text-to-Speech API_conversion-google-cloud-text-to-speech-api_tag_3233" not found or invalid function name
`
![Screenshot_20240125_110810](https://github.com/eworkers/K2ForJ4/assets/10660173/534b7244-d92e-4842-bd81-1592767e0af2)

The problem is probably initiated by the fact that the page has the rss feed enabled. But I'm not sure.

I should add that after the last commit, a very large cache size is formed again. Take a look at the screenshot, it's only half a day's worth of site activity:

![Screenshot_20240125_080722](https://github.com/eworkers/K2ForJ4/assets/10660173/2be6d445-d9f5-4562-b972-519f8f3cbcf6)

The problem appears from time to time, after clearing the cache the problem disappears.

**Comment by cmirnow** [comment]
I was forced to disable the cache. This error is repeated often. Joomla has caching issues always: perhaps this bug needs to be reported on joomla [github](https://github.com/joomla/joomla-cms/issues/42700)?

![Screenshot_20240126_134136](https://github.com/eworkers/K2ForJ4/assets/10660173/885f438a-8f40-4aa4-a43d-badab077b193)

**Comment by eworkers** [comment]
Please check the latest commit closes you issue.

> I should add that after the last commit, a very large cache size is formed again. Take a look at the screenshot, it's only half a day's worth of site activity

Things looks normal to me, you have a popular website that's all, the size looks (850 MB) normal for 59680 cached items. However i understand your concerns and i do think that k2 config should provide the option for users whether they prefer to disable com_k2_extended cache or no. Its a tradeoff matter for users when i comes to server resources. But this is not what this fork is about.

**Comment by cmirnow** [comment]
Unfortunately, it doesn't work. Right after installing the new K2 revision, enabling standard caching and clearing the cache, I got this error message.
But if the cache is turned off, K2ForJ4 works without problems.

Perhaps it makes a difference? - I don't use the system cache plugin, it's always turned off.

![k2_28012024](https://github.com/eworkers/K2ForJ4/assets/10660173/84af0f3f-6bcf-4126-92ea-0ead8158582c)

**Comment by eworkers** [comment]
please check if the latest push fixes your issue

**Comment by cmirnow** [comment]
I have two news stories. The first news is good news, the second news is bad news.

The bad news:
It took me 5 minutes to get this error again with caching enabled. Unfortunately, I see that the error also manifests itself when navigating to the K2 single article page.

Good news:
I enabled progressive cache instead of standard cache. And for half an hour I can't catch the error. It's weird and makes me wonder.
Maybe I'll get this error in an hour, or a day. I don't know. But maybe you'll find this information helpful as you work on your K2ForJ4 program code.

**Comment by cmirnow** [comment]
If I get this error with progressive caching enabled, I'll let you know about it.

**Comment by cmirnow** [comment]
Alas. I see that mistake again. But with progressive caching enabled, the error appears when clicking on the tags at the bottom of any K2 article.

**Comment by eworkers** [comment]
> Alas. I see that mistake again. But with progressive caching enabled, the error appears when clicking on the tags at the bottom of any K2 article.

please check [1c6012e]

**Comment by cmirnow** [comment]
> please check [[1c6012e](https://github.com/eworkers/K2ForJ4/commit/1c6012ef878854c07ac86d22ab4130ebf4740fd9)]

I have thoroughly tested the component with standard cache and progressive cache. It seems that this push solves all the problems. Thanks.

**Comment by cmirnow** [comment]
After clearing the cache, this problem sometimes occurs when navigating to a menu item formed by a tag. After the second click on this link, the problem disappears and does not manifest itself in the future.

I understand that Joomla caching has problems. Question: is it possible to fix this little mishap? If you think it is impossible, please close this issue.

**Comment by cmirnow** [comment]
Hmm. It could have been two hours of active work on the site since the previous error. Do you have an interpretation as to why the browser shows the saved error page just after clearing the Joomla cache?

**Comment by cmirnow** [comment]
https://github.com/eworkers/K2ForJ4/discussions/57
