### ISSUE TITLE
Category list: single and double quotes in Item Titles get converted in htm special characters code

### ISSUE THREAD

**Issue by krmrtrzv** [eworkers/K2ForJ4#58]
In category lists, if the title of a k2 item contains quotes, they get converted on the frontend into html chars code. At single item level there is no such problem.

**Comment by cmirnow** [comment]
Confirmed. I had a similar error.

**Comment by eworkers** [comment]
unable to produce, disable your override layouts if any and test, doesn't seem like a k2 issue (possible source of issue: override, custom template, 3rd party plugins...)

**Comment by cmirnow** [comment]
> Confirmed. I had a similar error.

Hmm, I tried to reproduce this problem on a test server, but I couldn't do it. But at some stage this problem has been.....

**Comment by krmrtrzv** [comment]
I solved it by activating k2 SEO - characters replacement. I know it should affect only urls, but that eliminated the html code
