### ISSUE TITLE
tag is not saved in the backend

### ISSUE THREAD

**Issue by krmrtrzv** [eworkers/K2ForJ4#65]
Hi, just created a new k2 item and when trying to assign a tag to it, I get the tag when autocompleteing it, but it does not respond when I hit enter, as was the usual behaviour. 
In k2 settings, the selected option for tags is: locked tags [no], Tagging system [Single input with auto-complete].
In browser console I got 3 errors:
Uncaught TypeError: a.browser is undefined
    jQuery 18
    <anonymous> https://mydomain.com/media/k2/assets/js/k2.backend.js?v=2.11.0&b=20220701&sitepath=/:420
    jQuery 2
Uncaught TypeError: Error resolving module specifier: editor-api [editors.js:1:58](https://tmydomain.com/media/system/js/editors/editors.js?f4cf88)
Uncaught TypeError: Error resolving module specifier: joomla.dialog [joomla-dialog-autocreate.js:1:25](https://mydomain.com/media/system/js/joomla-dialog-autocreate.js?96ce73)
Uncaught TypeError: Error resolving module specifier: editor-api [editor.module.js:5:7](https://mydomain.com/media/com_jce/editor/js/editor.module.js?1a08675feaa48681dd7f7a3cfb39632f)

I installed the latest version of K2ForJ4, Joomla is 5.0.3, PHP 8.1

The tagging works smoothly on old k2 items, but this problem appears only on this newly created item.

**Comment by eworkers** [comment]
please update and check if your issue remains. If latest update fixes your issue, please close this

**Comment by krmrtrzv** [comment]
Installing the latest version solved the problem, eventhough I created two more items where the issue persisted.

**Comment by krmrtrzv** [comment]
After successfuly adding a new k2 item and having the tags function restored in the backend. Now, when opening that saved item I again can not add tags - the ajax list of suggestions does not show up and whatever I write in the tags form filed does not save. Also, the attachments button is not active, so I can not add attachments. 
If I create a new item those issues are gone and I can add tags and attachments. 
Weird!
I have the same error in console: Uncaught TypeError: a.browser is undefined
    jQuery 18
    <anonymous> https://terziev.info/media/k2/assets/js/k2.backend.js?v=2.11.0&b=20220701&sitepath=/:420
    jQuery 2

Just installed the newest K2ForJ4, J is 5.0.3, PHP 8.1
I tried the suggested Alter sql command in PHPMyAdmin - no help. Permissions of media/k2/attachments are 755, files inside are 644...

**Comment by eworkers** [comment]
> After successfuly adding a new k2 item and having the tags function restored in the backend. Now, when opening that saved item I again can not add tags - the ajax list of suggestions does not show up and whatever I write in the tags form filed does not save. Also, the attachments button is not active, so I can not add attachments. If I create a new item those issues are gone and I can add tags and attachments. Weird! I have the same error in console: Uncaught TypeError: a.browser is undefined jQuery 18 https://terziev.info/media/k2/assets/js/k2.backend.js?v=2.11.0&b=20220701&sitepath=/:420 jQuery 2
> 
> Just installed the newest K2ForJ4, J is 5.0.3, PHP 8.1 I tried the suggested Alter sql command in PHPMyAdmin - no help. Permissions of media/k2/attachments are 755, files inside are 644...

This doesn't seem like a K2 issue, please disable 3rd party plugins if any and test again, also check if your browser is using some extensions that might be causing this.

**Comment by krmrtrzv** [comment]
I disabled JCE, JCH optimize, Simple Image Gallery Pro, AllVideos, and those are all 3rd party plugins installed on the site. Checked it on a different machine and with FF, Safari, Chrome. The result is the same. 
Finaly I realised that all items that have videos entered in the meia tab (no matter if youtube, vimeo, embeded or local/jw player) load with tags filed inactive (ajax gone), the attachments button - also inactive. All other items that have galleries, but does not have videos are loading as expected and I am able to add tags and attachments.

**Comment by eworkers** [comment]
> I disabled JCE, JCH optimize, Simple Image Gallery Pro, AllVideos, and those are all 3rd party plugins installed on the site. Checked it on a different machine and with FF, Safari, Chrome. The result is the same. Finaly I realised that all items that have videos entered in the MEDIA tab (no matter if youtube, vimeo, embeded or local/jw player) load with tags filed inactive (ajax gone), the attachments button - also inactive. All other items that have galleries, but does not have videos are loading as expected and I am able to add tags and attachments. Not sure if it matters - I have already dozen of sites updated with K2ForJ4, all with J4, where I got no similar issues. Only this site is upgraded to J5, and only on this one I have an issue.

This seems like JW AllVideos issue and not K2ForJ4, AllVideos is not fully compatible with J5, however check the last commit it should fix your issue.

**Comment by krmrtrzv** [comment]
Thanks so much! This solved the problem. I close this
