### ISSUE TITLE
Profile link doesn't work in comments

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#85]
Reproduce:

1. Log in to the site. (Joomla 5).
2. Go to the K2ForJ4&5 article page.
3. Leave a comment. I do not enter the name of the site (the field is left blank).

After posting a comment, my nickname has a link:

`https://my_website/component/k2/itemlist/user/64:user_name`

But if I click that link, the link redirects me to the main page of the site:

`https://my_website`

I could be wrong, of course. But I think this is a bug?
You can see it [here](https://masterpro.ws/vinaora-nivo-slider).

**Comment by eworkers** [comment]
It seems a routing matter, the user may have 0 K2 items posted and this is why it gets redirected to the home page

**Comment by cmirnow** [comment]
Hmm, but user Aleksej has a Joomla account, and he has a lot of comments. However, the redirect to the homepage is going on for him.

I should also add that this problem occurs whether the user is logged in Joomla or not.

**Comment by eworkers** [comment]
Correct me if I'm wrong, this is how things are with K2 official version, clicking on user inside K2 component always redirect to listing display of user's K2 items.

What you are suggesting is implementing a new view to summarize the user's profile and activity. Although it seems a good idea, this changes the purpose of this fork, which is to provide a workaround for K2-supported Joomla versions until an officially compatible version is released.

**Comment by cmirnow** [comment]
OK
