### ISSUE TITLE
K2 article pagination does not work after Joomla updates

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#90]
The statement in the title is my assumption. I suddenly found that after upgrading to Joomla 5.1.3 K2 pagination does not work: 404 - Component not found. This is probably a cause and effect issue. Disabling caching does not solve the problem.

The problem is very frustrating, please help. Mayday.

**Comment by cmirnow** [comment]
Yeah, that's correct. I rolled the site back to J5.1.2 and the pagination problem disappeared.
Info:
https://docs.joomla.org/Category:Version_5.1.3_FAQ

**Comment by eworkers** [comment]
Seems like this should be reported to Joomla's Dev team, however check if last commit fixes your issue as a temp solution

**Comment by cmirnow** [comment]
This commit fixes the pagination of K2 articles by category. It's working fine. But on all **tag pagination** link clicks, I get a blank page. There are no article titles and previews.

![k2j4](https://github.com/user-attachments/assets/62f9ad2f-a869-4186-ae1b-e12ddd07aaf2)

**Comment by cmirnow** [comment]
That seems to solve all the problems. Thank you.
